<?php
/*------------------------------------------------------------------------
# com_yoorecipe -  YooRecipe! Joomla 2.5 & 3.x recipe component
# ------------------------------------------------------------------------
# author    YooRock!
# copyright Copyright (C) 2011 yoorock.fr. All Rights Reserved.
# @license - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
# Websites: http://www.yoorecipe.com
# Technical Support:  Forum - http://www.yoorecipe.com/
-------------------------------------------------------------------------*/

// no direct access
defined('_JEXEC') or die ;

require_once( JPATH_ROOT . DIRECTORY_SEPARATOR . 'components' .DIRECTORY_SEPARATOR . 'com_komento' . DIRECTORY_SEPARATOR . 'komento_plugins' . DIRECTORY_SEPARATOR . 'abstract.php' );

class KomentoComYooRecipe extends KomentoExtension
{
	public $component = 'com_yoorecipe';
	public $_item;
	 
	public $_map = array(
		'id' => 'id',
		'title' => 'title',
		'catid' => 'cat_id',
		'permalink' => 'permalink',
		'hits' => 'nb_views',
		'created_by' => 'created_by'
	);
 
	public function __construct ($component) {
		
		$this->addFile( JPATH_ROOT . DIRECTORY_SEPARATOR . 'components' . DIRECTORY_SEPARATOR . 'com_yoorecipe' . DIRECTORY_SEPARATOR . 'helpers' . DIRECTORY_SEPARATOR .'html' . DIRECTORY_SEPARATOR . 'yoorecipehelperroute.php' );
		parent::__construct($component);
	}
	
	/**
	* load
	*/
	public function load( $cid )
    {
        static $instances = array();

        if( !isset( $instances[$cid] ) )
        {
			$yooRecipeparams 	= JComponentHelper::getParams('com_yoorecipe');
			$show_author_name 	= $yooRecipeparams->get('show_author_name', 'username');
			
			$author_name = '';
			if ($show_author_name == 'username') {
				$author_name = 'u.username';
			} else if ($show_author_name == 'name') {
				$author_name = 'u.name';
			}
			
			$db		= Komento::getDBO();
			$query	= 'SELECT a.id, a.title, a.alias, c.id as cat_id, a.created_by, '.$author_name.' as created_by_alias, a.nb_views,' //a.attribs
					. ' c.title AS category_title, c.alias AS category_alias,'
					. ' u.name AS author,'
					. ' parent.id AS parent_id, parent.alias AS parent_alias'
					. ' FROM ' . $db->nameQuote( '#__yoorecipe') . ' AS a'
					. ' LEFT JOIN ' . $db->nameQuote( '#__yoorecipe_categories' ) . ' AS cc ON cc.recipe_id = a.id'
					. ' LEFT JOIN ' . $db->nameQuote( '#__categories' ) . ' AS c ON c.id = cc.cat_id'
					. ' LEFT JOIN ' . $db->nameQuote( '#__users') . ' AS u ON u.id = a.created_by'
					. ' LEFT JOIN ' . $db->nameQuote( '#__categories') . ' AS parent ON parent.id = c.parent_id'
					. ' WHERE a.id = ' . $db->quote( (int) $cid );
			$db->setQuery( $query );

			if( !$result = $db->loadObject() )
			{
				return $this->onLoadArticleError( $cid );
			}

			$instances[$cid] = $result;
        }

        $this->_item = $instances[$cid];

        return $this;
    }

   /**
	* load
	*/
	public function getContentIds( $categories = '' )
    {
        $db		= Komento::getDBO();
		$query = '';

        if( empty( $categories ) )
        {
            $query = 'SELECT `id` FROM ' . $db->nameQuote( '#__yoorecipe' ) . ' ORDER BY `id`';
        }
        else
        {
            if( is_array( $categories ) )
            {
                $categories = implode( ',', $categories );
            }

            $query = 'SELECT `a.id` FROM ' . $db->nameQuote( '#__yoorecipe' ) . 'a INNER JOIN ' . $db->nameQuote( '#__yoorecipe_categories' ) . ' c on c.recipe_id = a.id WHERE `c.catid` IN (' . $categories . ') ORDER BY `a.id`';
        }

		$db->setQuery( $query );
		return $db->loadResultArray();
    }
	
	/**
	* load
	*/
    public function getCategories()
    {
		
		$db		= Komento::getDBO();
		$query	= 'SELECT a.id, a.title, a.level, a.parent_id'
				. ' FROM `#__categories` AS a'
				. ' WHERE a.extension = ' . $db->quote( 'com_yoorecipe' )
				. ' AND a.parent_id > 0'
				. ' ORDER BY a.lft';

		$db->setQuery( $query );
		$categories = $db->loadObjectList();

		foreach( $categories as &$row ) {
			$repeat = ( $row->level - 1 >= 0 ) ? $row->level - 1 : 0;
			$row->treename = str_repeat( '.&#160;&#160;&#160;', $repeat ) . ( $row->level - 1 > 0 ? '|_&#160;' : '' ) . $row->title;
		}

		return $categories;
    }

    /**
	* isListingView
	*/
	public function isListingView()
    {
		$views = array('recipes', 'categories', 'landingpage', 'search' );

		return in_array(JRequest::getCmd('view'), $views);
    }

    /**
	* isEntryView
	*/
	public function isEntryView()
    {
        return JRequest::getCmd('view') == 'recipe';
    }

    /**
	* onExecute
	*/
	public function onExecute( &$article, $html, $view, $options = array() )
    {
        // $html is the html content generated by Komento
        return $html;
    }
	
	public function getEventTrigger()
    {
        return 'onRecipeDisplay';
    }
	
	public function getAuthorName()
	{
		return $this->_item->author_name;
	}
	
	public function getContentPermalink()
	{
		$slug = $this->_item->alias ? ($this->_item->id.':'.$this->_item->title) : $this->_item->id;

		$link = JHTML::_('yoorecipehelperroute.getRecipeRoute', $slug, $catslug = 0); // no cat slug as yoorecipe supports multiple categories

		$link = $this->prepareLink( $link );

		return $link;
	}
}