</div>
<!-- //MAIN CONTENT -->

<!-- ARTICLE BOTTOM -->
<div class="article-bottom col-md-12">
<div class="t3-module module " id="Mod147">
<div class="module-inner">
<div class="module-ct" style="background: transparent;">

<div class="custom"  >
  <img src="http://placehold.it/940x400" alt="">
</div>
</div>
</div>
</div>
</div>
<!-- //ARTICLE BOTTOM -->
</div>

<!-- SIDEBAR 2 -->
<div class="t3-sidebar t3-sidebar-2 col-xs-6  col-md-3 ">
<div class="t3-module module " id="Mod138">
<div class="module-inner">
<div class="module-ct">

<div class="custom"  >
<img src="http://placehold.it/300x600" alt="">
</div>
</div>
</div>
</div>

<div class="t3-module module " id="Mod145">
<div class="module-inner">
<div class="module-ct">

<div class="custom"  >
<img src="http://placehold.it/300x600" alt="">
</div>
</div>
</div>
</div>
</div>
<!-- //SIDEBAR 2 -->

</div>
</div>

<!-- FOOTER -->
<footer id="t3-footer" class="wrap t3-footer">

<div class="container">
<div class="row">
<!-- FOOT NAVIGATION -->
<div class="col-xs-12 col-lg-12">
<!-- SPOTLIGHT -->
<div class="t3-spotlight t3-footnav  row">
<div class=" col-lg-3 col-md-3 col-sm-6 col-xs-12">
<div class="t3-module module " id="Mod106">
<div class="module-inner">
  <h3 class="module-title ">
    <span>More About Us</span>
  </h3>
  <div class="module-ct">
    <ul class="nav  nav-pills nav-stacked ">
      <li class="item-653">
        <a href="http://www.thinkhealthier.com/about-us.php" >About Us</a>
      </li>
      <li class="item-654">
        <a href="http://www.thinkhealthier.com/contact-us.php" >Contact Us</a>
      </li>
    </ul>
  </div>
</div>
</div>
</div>
<div class=" col-lg-3 col-md-3 col-sm-6 col-xs-12">
<div class="t3-module module " id="Mod107">
<div class="module-inner">
  <h3 class="module-title ">
    <span>Manage Subscriptions</span>
  </h3>
  <div class="module-ct">
    <ul class="nav nav-pills nav-stacked">
      <li class="item-651"><a href="http://www.thinkhealthier.com/change.php">Change My E-Mail Address</a></li>
      <li class="item-652"><a href="http://www.thinkhealthier.com/subscribe.php" style="display: inline;">Subscribe</a> | <a href="http://www.thinkhealthier.com/unsubscribe.php" style="display: inline;">Unsubscribe</a></li>
    </ul>
  </div>
</div>
</div>
</div>
<div class=" col-lg-3 col-md-3 col-sm-6 col-xs-12">
<div class="t3-module module " id="Mod108">
<div class="module-inner">
  <h3 class="module-title ">
    <span>Advertisers</span>
  </h3>
  <div class="module-ct">
    <ul class="nav  nav-pills nav-stacked ">
      <li class="item-649">
        <a href="http://www.thinkhealthier.com/advertising-standards.php" >Advertising Standards</a>
      </li>
      <li class="item-650">
        <a href="http://www.thinkhealthier.com/media-kit.php" >Media Kit</a>
      </li>
    </ul>
  </div>
</div>
</div>
</div>
<div class=" col-lg-3 col-md-3 col-sm-6 col-xs-6">
<div class="t3-module module -connect-footer " id="Mod109">
<div class="module-inner">
  <div class="module-ct">

    <div class="custom -connect-footer"  >
      <p style="text-align: right; margin: 0; padding: 0; margin-bottom: 11px;">
        Connect&nbsp;
        <a href="https://www.facebook.com/thinkhealthier/" target="_blank">
          <img src="http://www.thinkhealthier.com/images/fb.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
        </a>
        <a href="https://twitter.com/think_healthier" target="_blank">
          <img src="http://www.thinkhealthier.com/images/tw.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
        </a>
      </p>
    </div>
  </div>
</div>
</div>
<div class="t3-module module -search " id="Mod110">
<div class="module-inner">
  <div class="module-ct">
    <div class="search -search">
      <form action="http://www.thinkhealthier.com/" method="post" class="form-inline form-search">
        <label for="mod-search-searchword" class="element-invisible">Search ...</label>
        <input name="searchword" id="mod-search-searchword" maxlength="200"  class="form-control search-query" type="search" size="0" placeholder="Search" />
        <input type="image" alt="Search" class="button" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/searchButton.gif" onclick="this.form.searchword.focus();"/>
        <input type="hidden" name="task" value="search" />
        <input type="hidden" name="option" value="com_search" />
        <input type="hidden" name="Itemid" value="741" />
      </form>
    </div>
  </div>
</div>
</div>
</div>
</div>
<!-- SPOTLIGHT -->
</div>
<!-- //FOOT NAVIGATION -->

</div>
</div>

<section class="t3-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 copyright ">

<div class="custom"  >
<div style="text-align: center;">
<a href="#togglefooter" id="toggle-footer"> <i id="footer_show_hide" class="fa fa-caret-up fa-lg"></i>
</a>
&nbsp;&nbsp;Copyright © 2015. All rights reserved. ThinkHealthier is a trademark of Flatiron Media, LLC.&nbsp;
<a href="http://www.thinkhealthier.com/terms-of-service.php">Terms of Service</a>
|
<a href="http://www.thinkhealthier.com/privacy-policy.php">Privacy Policy</a>
</div>
</div>

</div>
</div>
</div>
</section>

</footer>
<!-- //FOOTER -->

</div>

</body>

</html>