<!DOCTYPE html>
<html lang="en-gb" dir="ltr" class='com_content view-article itemid-435 home j34 mm-hover '>

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="author" content="Super User" />
  <meta name="xclass" content="two-cols" />
  <title>Expert consistently zero copy legislation - ThinkHealthier</title>
  <link href="http://www.thinkhealthier.com/templates/ja_nuevo/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/bootstrap.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/system/css/system.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/template.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/megamenu.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/off-canvas.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/fonts/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,600italic,400italic,300italic" type="text/css" />
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/custom.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/print.css" type="text/css" />
  <link rel="stylesheet" href="http://www.thinkhealthier.com/templates/ja_nuevo/css/layouts/docs.css" type="text/css" />
  <script src="http://www.thinkhealthier.com/media/system/js/mootools-core.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/system/js/core.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/jui/js/jquery.min.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/jui/js/jquery-noconflict.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/jui/js/jquery-migrate.min.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/system/js/caption.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/bootstrap/js/bootstrap.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/js/jquery.tap.min.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/js/off-canvas.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/js/script.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/js/menu.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/jquery.infinitescroll.min.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/jquery.isotope.min.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/masonry.pkgd.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/imagesloaded.pkgd.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/script.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/templates/ja_nuevo/js/togglefooter.js" type="text/javascript"></script>
  <script src="http://www.thinkhealthier.com/media/system/js/html5fallback.js" type="text/javascript"></script>


  <!-- META FOR IOS & HANDHELD -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <style type="text/stylesheet">
    @-webkit-viewport   { width: device-width; }
    @-moz-viewport      { width: device-width; }
    @-ms-viewport       { width: device-width; }
    @-o-viewport        { width: device-width; }
    @viewport           { width: device-width; }
  </style>
  <script type="text/javascript">
    //<![CDATA[
    if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
      var msViewportStyle = document.createElement("style");
      msViewportStyle.appendChild(
        document.createTextNode("@-ms-viewport{width:auto!important}")
      );
      document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }
    //]]>
  </script>
  <meta name="HandheldFriendly" content="true"/>
  <meta name="apple-mobile-web-app-capable" content="YES"/>
  <!-- //META FOR IOS & HANDHELD -->

  <!-- Le HTML5 shim and media query for IE8 support -->
  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <script type="text/javascript" src="http://www.thinkhealthier.com/plugins/system/t3/base-bs3/js/respond.min.js"></script>
  <![endif]-->

</head>

<body class="">

  <div class="t3-wrapper">
    <!-- Need this wrapper for off-canvas menu. Remove if you don't use of-canvas -->

    <!-- HEADER -->
    <header id="t3-header" class="wrap t3-header">
      <div class="container">
        <div class="row">
          <!-- LOGO -->
          <div class="col-lg-6 col-md-6 col-xs-6 logo">
            <div class="logo-image">
              <a href="http://www.thinkhealthier.com/" title="">
                <img class="logo-img" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/logo.png" alt="ThinkHealthier" />
                <img class="logo-img logo-m" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/logo-m.png" alt="ThinkHealthier" />
                <span>ThinkHealthier</span>
              </a>
              <small class="site-slogan"></small>
            </div>
          </div>
          <!-- //LOGO -->

          <!-- OFFCANVAS -->
          <div class="pull-right">

            <button class="off-canvas-toggle " type="button" data-pos="right" data-nav="#t3-off-canvas" data-effect="off-canvas-effect-1">
              <img class="menu-open" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/menu-off-canvas.svg" />
            </button>

            <!-- OFF-CANVAS SIDEBAR -->
            <div id="t3-off-canvas" class="t3-off-canvas ">

              <div class="t3-off-canvas-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              </div>

              <div class="t3-off-canvas-body">
                <div class="t3-module module " id="Mod121">
                  <div class="module-inner">
                    <div class="module-ct">
                      <ul class="nav  nav-pills nav-stacked ">
                        <li class="item-435">
                          <a href="http://www.thinkhealthier.com/" >Home</a>
                        </li>
                        <li class="item-641">
                          <a href="http://www.thinkhealthier.com/todays-news" >Today's News</a>
                        </li>
                        <li class="item-638 deeper dropdown parent">
                          <a class="dropdown-toggle" href="http://www.thinkhealthier.com/conditions"  data-toggle="dropdown">
                            Conditions <em class="caret"></em>
                          </a>
                          <ul class="dropdown-menu">
                            <li class="item-672 parent">
                              <a href="http://www.thinkhealthier.com/conditions/eye-conditions" >Eye Conditions</a>
                            </li>
                            <li class="item-660">
                              <a href="http://www.thinkhealthier.com/conditions/menopause" >Menopause</a>
                            </li>
                            <li class="item-661 parent">
                              <a href="http://www.thinkhealthier.com/conditions/mental-health" >Mental Health</a>
                            </li>
                            <li class="item-662 parent">
                              <a href="http://www.thinkhealthier.com/conditions/bone-health" >Bone Health</a>
                            </li>
                            <li class="item-663">
                              <a href="http://www.thinkhealthier.com/conditions/cancer" >Cancer</a>
                            </li>
                            <li class="item-664">
                              <a href="http://www.thinkhealthier.com/conditions/diabetes" >Diabetes</a>
                            </li>
                            <li class="item-665 parent">
                              <a href="http://www.thinkhealthier.com/conditions/heart-disease" >Heart Disease</a>
                            </li>
                            <li class="item-666">
                              <a href="http://www.thinkhealthier.com/conditions/thyroid" >Thyroid</a>
                            </li>
                            <li class="item-667 parent">
                              <a href="http://www.thinkhealthier.com/conditions/digestive" >Digestive</a>
                            </li>
                            <li class="item-668 parent">
                              <a href="http://www.thinkhealthier.com/conditions/pain-management" >Pain Management</a>
                            </li>
                            <li class="item-669 parent">
                              <a href="http://www.thinkhealthier.com/conditions/respiratory" >Respiratory</a>
                            </li>
                            <li class="item-670 parent">
                              <a href="http://www.thinkhealthier.com/conditions/nervous-system" >Nervous System</a>
                            </li>
                            <li class="item-671 parent">
                              <a href="http://www.thinkhealthier.com/conditions/skin" >Skin</a>
                            </li>
                          </ul>
                        </li>
                        <li class="item-639">
                          <a href="http://www.thinkhealthier.com/healthy-recipes" >Healthy Recipes</a>
                        </li>
                        <li class="item-640 deeper dropdown parent">
                          <a class="dropdown-toggle" href="http://www.thinkhealthier.com/your-health"  data-toggle="dropdown">
                            Your Health <em class="caret"></em>
                          </a>
                          <ul class="dropdown-menu">
                            <li class="item-707">
                              <a href="http://www.thinkhealthier.com/your-health/diet-fitness" >Diet &amp; Fitness</a>
                            </li>
                            <li class="item-708">
                              <a href="http://www.thinkhealthier.com/your-health/nutrition" >Nutrition</a>
                            </li>
                            <li class="item-709">
                              <a href="http://www.thinkhealthier.com/your-health/sex-relationships" >Sex &amp; Relationships</a>
                            </li>
                            <li class="item-751">
                              <a href="http://www.thinkhealthier.com/your-health/sleep" >Sleep</a>
                            </li>
                            <li class="item-752">
                              <a href="http://www.thinkhealthier.com/your-health/wellness" >Wellness</a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="t3-module module -search " id="Mod123">
                  <div class="module-inner">
                    <div class="module-ct">
                      <div class="search -search">
                        <form action="http://www.thinkhealthier.com/" method="post" class="form-inline form-search">
                          <label for="mod-search-searchword" class="element-invisible">Search ...</label>
                          <input name="searchword" id="mod-search-searchword" maxlength="200"  class="form-control search-query" type="search" size="0" placeholder="Search" />
                          <input type="image" alt="Search" class="button" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/searchButton.gif" onclick="this.form.searchword.focus();"/>
                          <input type="hidden" name="task" value="search" />
                          <input type="hidden" name="option" value="com_search" />
                          <input type="hidden" name="Itemid" value="741" />
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="t3-module module " id="Mod124">
                  <div class="module-inner">
                    <div class="module-ct">

                      <div class="custom"  >
                        <p style="text-align: right;padding:0 24px;margin-top:-10px;">
                          <a href="https://www.facebook.com/thinkhealthier/" target="_blank">
                            <img src="http://www.thinkhealthier.com/images/fb.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
                          </a>
                          &nbsp;
                          <a href="https://twitter.com/think_healthier" target="_blank">
                            <img src="http://www.thinkhealthier.com/images/tw.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
                          </a>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <!-- //OFF-CANVAS SIDEBAR --> </div>
          <!-- //OFFCANVAS -->

          <!-- RIGHT MODS -->
          <div id="right-mods" class="col-lg-6 col-md-6 col-xs-6">
            <div class="t3-nav-btn pull-right">

              <!-- OFF SIDEBAR WAS HERE -->

              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header pull-right"></div>

              <!-- SEARCH -->
              <div class="-search">
                <div class="moduletable">

                  <div class="custom"  >
                    <p style="text-align: right; margin: 0; padding: 0; margin-bottom: 11px; font-weight: 600;">
                      Connect&nbsp;
                      <a href="https://www.facebook.com/thinkhealthier/" target="_blank">
                        <img src="http://www.thinkhealthier.com/images/fb.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
                      </a>
                      <a href="https://twitter.com/think_healthier" target="_blank">
                        <img src="http://www.thinkhealthier.com/images/tw.svg" alt="" width="30" height="30" style="vertical-align: middle;" />
                      </a>
                    </p>
                  </div>
                </div>
                <div class="moduletable">
                  <div class="search">
                    <form action="http://www.thinkhealthier.com/" method="post" class="form-inline form-search">
                      <label for="mod-search-searchword" class="element-invisible">Search ...</label>
                      <input name="searchword" id="mod-search-searchword" maxlength="200"  class="form-control search-query" type="search" size="0" placeholder="Search" />
                      <input type="image" alt="Search" class="button" src="http://www.thinkhealthier.com/templates/ja_nuevo/images/searchButton.gif" onclick="this.form.searchword.focus();"/>
                      <input type="hidden" name="task" value="search" />
                      <input type="hidden" name="option" value="com_search" />
                      <input type="hidden" name="Itemid" value="741" />
                    </form>
                  </div>
                </div>

              </div>
              <!-- //HEAD SEARCH --> </div>

            <div class="navbar navbar-default t3-mainnav pull-right"></div>

         </div>
      </div>
    </header>
    <!-- //HEADER -->

    <!-- MAIN NAVIGATION -->
    <nav id="t3-mainnav" class="wrap" style="width:100%;">

      <div class="navbar navbar-default t3-mainnav container">

        <div class="t3-navbar navbar-collapse collapse row">
          <div  class="t3-megamenu animate slide"  data-duration="350" data-responsive="true">
            <ul class="nav navbar-nav level0">
              <li class="mega-align-justify" data-id="435" data-level="1" data-alignsub="justify">
                <a class="" href="http://www.thinkhealthier.com/"   data-target="#">Home</a>

              </li>
              <li class="mega-align-justify" data-id="641" data-level="1" data-alignsub="justify">
                <a class="" href="http://www.thinkhealthier.com/todays-news"   data-target="#">Today's News</a>

              </li>
              <li class="mega-align-justify" data-id="638" data-level="1" data-alignsub="justify">
                <a class="" href="http://www.thinkhealthier.com/conditions"   data-target="#" >Conditions</a>

              </li>
              <li  data-id="639" data-level="1">
                <a class="" href="http://www.thinkhealthier.com/healthy-recipes"   data-target="#">Healthy Recipes</a>

              </li>
              <li class="mega-align-justify" data-id="640" data-level="1" data-alignsub="justify">
                <a class="" href="http://www.thinkhealthier.com/your-health"   data-target="#" >Your Health</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    
</nav>
<!-- //MAIN NAVIGATION -->
