<div id="t3-mainbody" class="container t3-mainbody" style="padding-top: 10px;">
<div class="row">

<div class="main-content-sidebar-left col-xs-12 col-md-9">

	<!-- SIDEBAR 1 -->
	<div class="t3-sidebar t3-sidebar-1 col-xs-6 col-md-4">
	<div class="t3-module module healthy-advice " id="Mod137">
	<div class="module-inner">
	<div class="module-ct">

	<div class="custom healthy-advice"  >
	  <img src="http://placehold.it/300x168" alt="">
	</div>

	</div>
	</div>
	</div>
	<div class="t3-module module " id="Mod139">
	<div class="module-inner">
	<div class="module-ct">

	<div class="custom"  >
	  <img src="http://placehold.it/300x600" alt="">
	</div>
	</div>
	</div>
	</div>
	</div>
	<!-- //SIDEBAR 1 -->

	<!-- MAIN CONTENT -->
	<div id="t3-content" class="t3-content col-xs-12 col-md-8">
		
